server:
  port: 8085

spring:
  application:
    name: notification-service
  config:
    import: configserver:http://localhost:8888/
  kafka:
    topic:
      name: notificationTopic
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer