server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9095/eureka/

#
#logging:
#  level:
#    ROOT: DEBUG