eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9095/eureka}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootProject
    username: postgres
    password: admin
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

application-description: SpringBoot Project 2024
application-license: API Licence
application-version: 1.0