spring:
  application:
    name: eureka-server

server:
  port: 9095

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:9095/eureka